language: java
before_install:
- npm install -g @angular/cli
- npm install
jdk:
- oraclejdk8
script:
- ./gradlew build
- ng build --prod
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  app: bar-startup
  api_key: $API_KEY
  skip_cleanup: true