language: java
before_install:
- npm install -g @angular/cli
- cd ./frontend && npm install && cd ../
jdk:
- oraclejdk8
script:
- ./gradlew build
- cd ./frontend && ng build --prod && cd ../
cache:
  directories:
  - $HOME/.gradle
deploy:
  provider: heroku
  app: bar-startup
  api_key: $API_KEY
  skip_cleanup: true