spring:
  data:
    mongodb:
      uri: mongodb://localhost:12345/test

auth0:
    issuer: https://b741c6db15e1.eu.auth0.com/
    audience: b741c6db15e1.bar-app

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://vova:test@ds161194.mlab.com:61194/heroku_14x1d1bz
